FROM node:14-alpine3.12
RUN npm install --global conventional-changelog-cli conventional-changelog-angular \
 && apk add --no-cache --upgrade git
ENTRYPOINT ["/usr/local/bin/conventional-changelog"]
CMD ["--help"]
